In [0]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [0]:
steps=[("standard scaler",StandardScaler()),("Classifier",LogisticRegression())]

In [0]:
steps

[('standard scaler', StandardScaler()), ('Classifier', LogisticRegression())]

In [0]:
pipe=Pipeline(steps)

In [0]:
from sklearn import set_config

In [0]:
set_config(display="diagram")
pipe

Pipeline(steps=[('standard scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [0]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000)

In [0]:
x.shape

(1000, 20)

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)


In [0]:
x_train

array([[-1.38314364,  0.06620149,  1.49409737, ...,  0.02754427,
        -0.57822309, -0.56168467],
       [-0.40689185,  1.00947198, -0.67875261, ...,  1.63317888,
         1.04780879,  1.95316581],
       [ 0.43243832,  0.25016212,  1.56017273, ...,  1.7939085 ,
        -0.11265224,  0.352245  ],
       ...,
       [ 0.35823855,  0.24270781, -0.68769848, ..., -1.32500062,
         0.99947185, -0.24247943],
       [-0.17059255, -1.23375047, -2.83161064, ...,  0.33913696,
        -0.08264213, -0.62040564],
       [ 0.47837503,  0.90679137,  1.16336123, ..., -0.66510854,
         1.1292915 , -1.06422283]])

In [0]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('standard scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [0]:
Pipeline(steps=[('standard scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])
y_predict=pipe.predict(x_test)
y_predict

array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,

In [0]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [0]:
steps=[('Scaling',StandardScaler()),
       ('PCA',PCA()),
       ('classifier',SVC())]
pipe2=Pipeline(steps)
pipe2.fit(x_train,y_train)
Pipeline(steps=[('Scaling', StandardScaler()),
                ('PCA', PCA()),
                ('classifier', SVC())])
pipe2.predict(x_train)

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,

In [0]:
from sklearn.impute import SimpleImputer
import numpy as np

In [0]:
numeric_processor = Pipeline(steps=['imputation',SimpleImputer(missing_values=np.nan,strategy='mean'),('scaler',StandardScaler())])
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(

steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
 ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)
categorical_processor


Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [0]:
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer(
 [("categorical",categorical_processor,["gender","City"]),
 ("numerical",numeric_processor,["age","height"])]
)
preprocessor
ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),
 ('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
 ['gender', 'City']),
 ('numerical',
 Pipeline(steps=[('imputation_mean',
 SimpleImputer()),
 ('scaler',
StandardScaler())]),
 ['age', 'height'])])


ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [0]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe
Pipeline(steps=[('columntransformer',
 ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),

('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
 ['gender', 'City']),
 ('numerical',

Pipeline(steps=[('imputation_mean',

SimpleImputer()),

('scaler',
StandardScaler())]),
 ['age',
'height'])])),
 ('logisticregression', LogisticRegression())])


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])