In [2]:
import numpy as np

In [6]:
ids=np.random.randint(0,9,size=(15))
ids

array([1, 8, 2, 4, 7, 2, 8, 8, 5, 7, 7, 6, 6, 7, 5])

In [8]:
_,c=np.unique(ids,return_index=(True))
_,c

(array([1, 2, 4, 5, 6, 7, 8]),
 array([ 0,  2,  3,  8, 11,  4,  1], dtype=int64))

In [ ]:
oiginal=np.full(ids.shape,True)
original[np.sort(ids)]=False