In [ ]:
import tensorflow as tf
print('tensorflow',format(tf.__version__))


tensorflow 2.18.0


In [ ]:
d0=tf.constant(1)
print("Dimension is",tf.rank(d0).numpy())
print(d0)

Dimension is 0
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
d1=tf.ones((2,))
print("Dimension is", tf.rank(d1).numpy())
print(d1)

Dimension is 1
tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [ ]:
d2 = tf.ones((2,2))
print("Dimension is", tf.rank(d2).numpy())
print(d2)

Dimension is 2
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
d3 =tf.ones((2,2,2))
print("Dimension is", tf.rank(d3).numpy())
print(d3)


Dimension is 3
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [ ]:
x1 = tf.Variable(23)
x2 = tf.Variable([ [ [0.,1.,2.], [3.,4.,5.]], [[6.,7.,8.], [9.,10.,11.]]])
x0 =123
x1


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [ ]:
x1 = tf.constant(100)
print(x1)

tf.Tensor(100, shape=(), dtype=int32)


In [ ]:
x112 =tf.reshape(x2,[1,12])
x112


<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

In [ ]:
xf64 =tf.Variable(202,dtype=tf.float64)
xf64.dtype
xf64.numpy()

np.float64(202.0)

In [ ]:
tf.rank(xf64)
tf.rank(x2)
t = tf.constant([[[1,1,1],[2,2,2]],[[4,3,5],[4,4,414]]])
tf.rank(t).numpy()
t.numpy()

array([[[  1,   1,   1],
        [  2,   2,   2]],

       [[  4,   3,   5],
        [  4,   4, 414]]], dtype=int32)

In [ ]:
tensor3 =t[1,1,2]
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=414>

In [ ]:
x= tf.constant([0,1,1,2,3,4,8,13,21,34])
print("Before 4:",x[:4].numpy())
print("After 4:",x[4:].numpy())
print("From 2, before 7:",x[2:7].numpy())
print("Every other item:",x[::2].numpy())
print("Reversed:",x[::-1].numpy())

Before 4: [0 1 1 2]
After 4: [ 3  4  8 13 21 34]
From 2, before 7: [1 2 3 4 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  4  3  2  1  1  0]


In [ ]:
a =tf.constant([[1,2],[3,4]])
i= tf.cast(a,dtype=tf.float32)
print(a)
print(i)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
#Tensor Operation
a= tf.constant([[1,2],[3,4]])
b= tf.constant([[5,6],[7,8]])
c = a +b
a.numpy()
b.numpy()
print(a)
print(b)
print("\n output of c",c)
d =tf.square(c)
print(d)
tf.add(a,b)
tf.subtract(b,a)
e= a*b
print(6)
tf.multiply(a,b) # No of columns in a == No of Rows in b tensor

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)

 output of c tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 36  64]
 [100 144]], shape=(2, 2), dtype=int32)
6


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>